"""empty message

Revision ID: b073d18540c2
Revises: bd42f65f027d
Create Date: 2021-10-28 14:29:13.749730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b073d18540c2'
down_revision = 'bd42f65f027d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('biznum',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_constraint('uq_user_biznum', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_biznum', ['biznum'])
        batch_op.alter_column('biznum',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
