"""empty message

Revision ID: bd42f65f027d
Revises: 074c4395b59c
Create Date: 2021-10-28 14:22:14.749531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd42f65f027d'
down_revision = '074c4395b59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biznum', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('rankcd', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('deptcd', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('phonenum', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hidt', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('redt', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_biznum'), ['biznum'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_biznum'), type_='unique')
        batch_op.drop_column('redt')
        batch_op.drop_column('hidt')
        batch_op.drop_column('phonenum')
        batch_op.drop_column('deptcd')
        batch_op.drop_column('rankcd')
        batch_op.drop_column('biznum')

    # ### end Alembic commands ###
